const BOTTOM_HORIZONTAL_ALIGNED = 'BOTTOM_HORIZONTAL_ALIGNED'
const TOP_HORIZONTAL_ALIGNED = 'TOP_HORIZONTAL_ALIGNED'
const HORIZONTAL_SEGMENTS = 'HORIZONTAL_SEGMENTS'
const VERTICAL_SEGMENTS = 'VERTICAL_SEGMENTS'

exports.BOTTOM_HORIZONTAL_ALIGNED = BOTTOM_HORIZONTAL_ALIGNED
exports.TOP_HORIZONTAL_ALIGNED = TOP_HORIZONTAL_ALIGNED
exports.VERTICAL_SEGMENTS = VERTICAL_SEGMENTS
exports.HORIZONTAL_SEGMENTS = HORIZONTAL_SEGMENTS
